backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "artykuly" # Used in routes, e.g., /admin/collections/artykuly
    label: "Artykuły" # Used in the UI
    folder: "src/routes/artykuly" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}" # Filename template, e.g., YYYY/MM/DD/title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Meta description", name: "metaDescription", widget: "string" }
      - { label: "Yoast keyword", name: "yoastKeyword", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Obraz główny", name: "thumbnail", widget: "image" }
      - {
          label: "Tagi",
          name: "tags",
          widget: "list",
          field: { label: "Tag", name: "tag", widget: "string" },
          required: false,
        }
      - { label: "Tekst", name: "body", widget: "markdown" }

  - name: "oferta"
    label: "Oferta"
    folder: "src/routes/oferta"
    create: true
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Meta description", name: "metaDescription", widget: "string" }
      - { label: "Yoast keyword", name: "yoastKeyword", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Tekst", name: "body", widget: "markdown" }
      - { label: "Cena", name: "price", widget: "string" }

  - name: "szkolenia"
    label: "Szkolenia"
    folder: "src/routes/szkolenia"
    create: true
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Meta description", name: "metaDescription", widget: "string" }
      - { label: "Yoast keyword", name: "yoastKeyword", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Poziom zaawansowania", name: "level", widget: "string" }
      - { label: "Tekst", name: "body", widget: "markdown" }
      - { label: "Cena regularna", name: "price", widget: "string" }
      - {
          label: "Cena przy wcześniejszym zapisie",
          name: "priceReduced",
          widget: "string",
          required: false,
        }

  - name: "zespol"
    label: "Zespół"
    folder: "src/routes/zespol"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Imię i nazwisko", name: "title", widget: "string" }
      - { label: "Zdjęcie", name: "photo", widget: "image" }
      - { label: "Opis", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Info"
    create: false
    slug: "{{slug}}"
    files:
      - name: "onas"
        file: "src/routes/onas/onas.md"
        label: "O Art Division"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - { label: "Opis", name: "body", widget: "markdown" }
          - { label: "Obraz główny", name: "thumbnail", widget: "image" }
      - name: "kontakt"
        file: "src/routes/kontakt.md"
        label: "Kontakt"
        fields:
          - {
              label: "Dane kontaktowe (shift + enter by przejść do nowej linii)",
              name: "body",
              widget: "markdown",
            }
      - name: "polityka-prywatnosci"
        file: "src/routes/polityka-prywatnosci.md"
        label: "Polityka prywatności"
        fields:
          - { label: "Tekst", name: "body", widget: "markdown" }
